import Head from 'next/head'
import Menu from "./Menu"
import styles from "../styles/Layout.module.scss";


const Layout = ({children, pagina}) => {
  
  return (
    <>
      <Head>
        <title>SuarezDev - {pagina}</title>
        <meta name="description" content="Generated by create next app" />
        <meta charset="utf-8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container} id="main">
        <div className={styles.menu}>
          <Menu 
            pagina={pagina}
          />
        </div>
        <div 
          className={styles.children}
        >{children}</div>
      </main>
    </>
  )
}

export default Layout